[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
  from = "/api/rpc"
  to = "/.netlify/functions/rpc"
  status = 200
  force = true

[[redirects]]
  from = "/api/rpc-fallback"
  to = "/.netlify/functions/rpc-fallback"
  status = 200
  force = true