/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20Minimal__factory>
getContractFactory(name: 'VWalaFixedSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VWalaFixedSwap__factory>
getContractFactory(name: 'IERC20BalanceOnly', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20BalanceOnly__factory>
getContractFactory(name: 'VWalaReserveVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VWalaReserveVault__factory>
getContractFactory(name: 'WalaFixedToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WalaFixedToken__factory>
getContractFactory(name: 'WalaTokenFactory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WalaTokenFactory__factory>

  getContractAt(name: 'IERC20Minimal', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20Minimal>
getContractAt(name: 'VWalaFixedSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VWalaFixedSwap>
getContractAt(name: 'IERC20BalanceOnly', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20BalanceOnly>
getContractAt(name: 'VWalaReserveVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VWalaReserveVault>
getContractAt(name: 'WalaFixedToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WalaFixedToken>
getContractAt(name: 'WalaTokenFactory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WalaTokenFactory>

  deployContract(name: 'IERC20Minimal', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'VWalaFixedSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VWalaFixedSwap>
deployContract(name: 'IERC20BalanceOnly', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20BalanceOnly>
deployContract(name: 'VWalaReserveVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VWalaReserveVault>
deployContract(name: 'WalaFixedToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalaFixedToken>
deployContract(name: 'WalaTokenFactory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalaTokenFactory>

  deployContract(name: 'IERC20Minimal', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20Minimal>
deployContract(name: 'VWalaFixedSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VWalaFixedSwap>
deployContract(name: 'IERC20BalanceOnly', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20BalanceOnly>
deployContract(name: 'VWalaReserveVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VWalaReserveVault>
deployContract(name: 'WalaFixedToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalaFixedToken>
deployContract(name: 'WalaTokenFactory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WalaTokenFactory>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  