/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vWalaFixedSwapSol from './VWalaFixedSwap.sol/index.js';
export type { vWalaFixedSwapSol };
import type * as vWalaReserveVaultSol from './VWalaReserveVault.sol/index.js';
export type { vWalaReserveVaultSol };
export type { WalaFixedToken } from './WalaFixedToken.js';
export type { WalaTokenFactory } from './WalaTokenFactory.js';
export * as factories from './factories/index.js';
export type { IERC20Minimal } from './VWalaFixedSwap.sol/IERC20Minimal.js';
export { IERC20Minimal__factory } from './factories/VWalaFixedSwap.sol/IERC20Minimal__factory.js';
export type { VWalaFixedSwap } from './VWalaFixedSwap.sol/VWalaFixedSwap.js';
export { VWalaFixedSwap__factory } from './factories/VWalaFixedSwap.sol/VWalaFixedSwap__factory.js';
export type { IERC20BalanceOnly } from './VWalaReserveVault.sol/IERC20BalanceOnly.js';
export { IERC20BalanceOnly__factory } from './factories/VWalaReserveVault.sol/IERC20BalanceOnly__factory.js';
export type { VWalaReserveVault } from './VWalaReserveVault.sol/VWalaReserveVault.js';
export { VWalaReserveVault__factory } from './factories/VWalaReserveVault.sol/VWalaReserveVault__factory.js';
export { WalaFixedToken__factory } from './factories/WalaFixedToken__factory.js';
export { WalaTokenFactory__factory } from './factories/WalaTokenFactory__factory.js';