/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface WalaTokenFactoryInterface extends Interface {
    getFunction(nameOrSignature: "createToken" | "getTokensByCreator"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TokenCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createToken', values: [string, string, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'getTokensByCreator', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokensByCreator', data: BytesLike): Result;
  }

  
    export namespace TokenCreatedEvent {
      export type InputTuple = [creator: AddressLike, owner: AddressLike, token: AddressLike, name: string, symbol: string, wholeSupply: BigNumberish, metadataURI: string];
      export type OutputTuple = [creator: string, owner: string, token: string, name: string, symbol: string, wholeSupply: bigint, metadataURI: string];
      export interface OutputObject {creator: string, owner: string, token: string, name: string, symbol: string, wholeSupply: bigint, metadataURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface WalaTokenFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): WalaTokenFactory;
    waitForDeployment(): Promise<this>;

    interface: WalaTokenFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createToken: TypedContractMethod<
      [name_: string, symbol_: string, wholeSupply_: BigNumberish, owner_: AddressLike, metadataURI_: string, ],
      [string],
      'nonpayable'
    >
    

    
    getTokensByCreator: TypedContractMethod<
      [creator_: AddressLike, ],
      [string[]],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createToken'): TypedContractMethod<
      [name_: string, symbol_: string, wholeSupply_: BigNumberish, owner_: AddressLike, metadataURI_: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokensByCreator'): TypedContractMethod<
      [creator_: AddressLike, ],
      [string[]],
      'view'
    >;

    getEvent(key: 'TokenCreated'): TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;

    filters: {
      
      'TokenCreated(address,address,address,string,string,uint256,string)': TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
      TokenCreated: TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
    
    };
  }