/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vWalaFixedSwapSol from './VWalaFixedSwap.sol/index.js';
export * as vWalaReserveVaultSol from './VWalaReserveVault.sol/index.js';
export { WalaFixedToken__factory } from './WalaFixedToken__factory.js';
export { WalaTokenFactory__factory } from './WalaTokenFactory__factory.js';