/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20BalanceOnly } from './IERC20BalanceOnly.js';
export type { VWalaReserveVault } from './VWalaReserveVault.js';