/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface VWalaReserveVaultInterface extends Interface {
    getFunction(nameOrSignature: "nativeBalance" | "tokenBalance"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "NativeDeposited"): EventFragment;

    encodeFunctionData(functionFragment: 'nativeBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenBalance', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'nativeBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenBalance', data: BytesLike): Result;
  }

  
    export namespace NativeDepositedEvent {
      export type InputTuple = [from: AddressLike, amount: BigNumberish];
      export type OutputTuple = [from: string, amount: bigint];
      export interface OutputObject {from: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VWalaReserveVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): VWalaReserveVault;
    waitForDeployment(): Promise<this>;

    interface: VWalaReserveVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    nativeBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    tokenBalance: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'nativeBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'tokenBalance'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'NativeDeposited'): TypedContractEvent<NativeDepositedEvent.InputTuple, NativeDepositedEvent.OutputTuple, NativeDepositedEvent.OutputObject>;

    filters: {
      
      'NativeDeposited(address,uint256)': TypedContractEvent<NativeDepositedEvent.InputTuple, NativeDepositedEvent.OutputTuple, NativeDepositedEvent.OutputObject>;
      NativeDeposited: TypedContractEvent<NativeDepositedEvent.InputTuple, NativeDepositedEvent.OutputTuple, NativeDepositedEvent.OutputObject>;
    
    };
  }