/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Minimal } from './IERC20Minimal.js';
export type { VWalaFixedSwap } from './VWalaFixedSwap.js';