/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC20BalanceOnly, IERC20BalanceOnlyInterface } from "../../VWalaReserveVault.sol/IERC20BalanceOnly.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "balanceOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IERC20BalanceOnly__factory {
    static readonly abi = _abi;
    static createInterface(): IERC20BalanceOnlyInterface {
      return new Interface(_abi) as IERC20BalanceOnlyInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IERC20BalanceOnly {
      return new Contract(address, _abi, runner) as unknown as IERC20BalanceOnly;
    }
  }
  