/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20BalanceOnly__factory } from './IERC20BalanceOnly__factory.js';
export { VWalaReserveVault__factory } from './VWalaReserveVault__factory.js';