/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { VWalaReserveVault, VWalaReserveVaultInterface } from "../../VWalaReserveVault.sol/VWalaReserveVault.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "NativeDeposited",
    "type": "event"
  },
  {
    "stateMutability": "payable",
    "type": "fallback"
  },
  {
    "inputs": [],
    "name": "nativeBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "tokenBalance",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b506101bd8061001d5f395ff3fe60806040526004361061002c575f3560e01c8063865fc5011461009b578063eedc966a146100bb57610069565b366100695760405134815233907fb5d7700fb0cf415158b8db7cc7c39f0eab16a825c92e221404b4c8bb099b4bbb906020015b60405180910390a2005b60405134815233907fb5d7700fb0cf415158b8db7cc7c39f0eab16a825c92e221404b4c8bb099b4bbb9060200161005f565b3480156100a6575f80fd5b50475b60405190815260200160405180910390f35b3480156100c6575f80fd5b506100a96100d5366004610143565b6040516370a0823160e01b81523060048201525f906001600160a01b038316906370a0823190602401602060405180830381865afa158015610119573d5f803e3d5ffd5b505050506040513d601f19601f8201168201806040525081019061013d9190610170565b92915050565b5f60208284031215610153575f80fd5b81356001600160a01b0381168114610169575f80fd5b9392505050565b5f60208284031215610180575f80fd5b505191905056fea26469706673582212203358b07d217182c489c90a09af9e420881f9face8f6d5d452845b30c7b9ff91864736f6c63430008180033";

  
      type VWalaReserveVaultConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: VWalaReserveVaultConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class VWalaReserveVault__factory extends ContractFactory {
    
      constructor(...args: VWalaReserveVaultConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<VWalaReserveVault & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): VWalaReserveVault__factory {
      return super.connect(runner) as VWalaReserveVault__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): VWalaReserveVaultInterface {
      return new Interface(_abi) as VWalaReserveVaultInterface;
    }
    
    override attach(address: string | Addressable): VWalaReserveVault {
      return super.attach(address) as VWalaReserveVault;
    }
  static connect(address: string, runner?: ContractRunner | null): VWalaReserveVault {
      return new Contract(address, _abi, runner) as unknown as VWalaReserveVault;
    }
  }

  
  